[package]
name = "filescope"
version = "0.3.1"
description = "FileScope Windows desktop application by Veilbyte"
authors = ["Veilbyte"]
edition = "2021"
license-file = "../../../LICENSE"
repository = "https://github.com/Veilbyte/FileScope"
homepage = "https://github.com/Veilbyte/FileScope"

[lib]
name = "filescope_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
sha2 = "0.10"
uuid = { version = "1", features = ["v4", "serde"] }
url = { version = "2", features = ["serde"] }
goblin = "0.9"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["net", "time"] }

[dev-dependencies]
tempfile = "3"
